### PR TITLE
GTT Import-Export 

### PR DESCRIPTION
**Pull request by mbasa-geolonia**
This adds GTT import-export functionalities into SMASH.

### CODE REVIEW

**Comment by mbasa-geolonia** [comment]
@moovida, hi. I know you are very busy but we'll really appreciate it if you can take a very quick look on this pr and see if there are portions that might need modifications. 

Thanks.

**Comment by moovida** [comment]
Hi @mbasa-georepublic , sorry, I really forgot to handle this due to various issues.

What I need for this to be included, is a documentation that explains how to use it, both app and server-side. 
Otherwise it will be just a new entry and no one will ever use it.

Do you have something to share? We can also place it here in the WIKI and I will then migrate it to the official documentation.
Obviously a PR on the usermanual [0] would be the best.

What do you think?

Sorry again for the late reply.


[0] https://github.com/geopaparazzi/usermanual

**Comment by mbasa-geolonia** [comment]
Hello @moovida. We are consolidating right now the GTT documentation and will get back to you once that is done. 

We can create a PR on the geopaparazzi/usermanual, but it seems it hasn't been updated in over 2 years. Is there an updated one for SMASH?

**Comment by mbasa-geolonia** [comment]
Daniel wrote a Redmine + SMASH integration here: 

https://github.com/gtt-project/redmine_gtt_smash/blob/main/doc/getting-started.md

**Comment by moovida** [comment]
Great @mbasa-georepublic , thanks. I should be able to merge within the next few days. I will copy the doc of Daniel over to the official doc, is that ok, for you?

**Comment by moovida** [comment]
Actually, since I reviewed this already, I can also merge right away and then work on the docs later when I do a release.

**Pull request merged**
