### PR TITLE
Changed to subtitle so pull-down is at bottom

### PR DESCRIPTION
**Pull request by sanak**
Supports https://github.com/gtt-project/smash_import_export_plugins/issues/11

@moovida (CC: @mbasa, @nobnisai, @tanja, @dkastl)
We are adjusting GTT Export screen's layout now, so please wait for a while. 🙇‍♂️

### CODE REVIEW

**Comment by sanak** [comment]
@mbasa, @nobnisai 
I just added a commit which supports the followings.
- Concatenate messages below `Sync Stats` with enough padding.
- Wrap ListView by padding: 8 (`SmashUI.DEFAULT_PADDING`).
- Add SizedBox(height: 8 or 16) before each ListTile as spacer.
- Set DropDownButton `isExpanded: true` to show dropdown inverted triangle at most right.
adjust-gtt-export-ui

Note that FlutterFlow is not fully compatible with actual Flutter ListTile part (DropdownButton as subtitle), so the result design is a bit different from FlutterFlow design...

If you are okay, then I will set ready for review.
Thanks,

**Comment by sanak** [comment]
Well, I set ready for review. 😄

**Comment by moovida** [comment]
Sorry @sanak , thought from the emails this was on the GTT repo :-D

**Comment by sanak** [comment]
Okay, no problem.
Thanks! 😄🙇‍♂️

**Pull request merged**
